Added so it encrypt before sending

diff --git a/backupCopy b/backupCopy
--- a/backupCopy
+++ b/backupCopy
@@ -24,7 +24,11 @@ cp_user=""
 
 ########################### Don't touch the below code ##############################
 
-if [ "$cp_pass" = "" -o "$cp_user" = "" ]; then
+## Make some checks the script needs to run.
+if [ "$(which {gpg,dialog} &> /dev/null;echo $?)" = "1" ]; then
+	echo "missing a dependency to run the script. Make sure to have 'gpg' and 'dialog' installed."
+	exit 1
+elif [ "$cp_pass" = "" -o "$cp_user" = "" ]; then
 	echo "The username or password has not been set. Edit script and enter your credentials."
 	exit 1
 fi
@@ -34,7 +38,7 @@ CopyCmd="CopyCmd Cloud -password=$cp_pass -username=$cp_user"
 ## Select the local dir to backup and then destination dir on Copy.
 dialog --title "Info" --msgbox "To select which directory to backup use the arrow keys\nwhen navigating. Then hit space key to select and return\nkey to confirm.\n\nYou can also enter the path to the directory directly." 10 60
 locl_dir=$(dialog --stdout --title "Local directory to backup" --dselect $HOME 20 60)
-dest_dir=$(dialog --stdout --title "Destination on Copy" --inputbox "\nEnter the destination directory on Copy.com for\nwhich you want to backup to.\n\n" 20 60)
+dest_dir=$(dialog --stdout --title "Destination on Copy" --inputbox "\nEnter the destination directory on Copy.com for which you want\nto backup to.\n\n" 12 70)
 clear
 
 ## Abort if dest_dir is empty.
@@ -53,33 +57,39 @@ if ! echo $locl_dir | grep -G "/$"; then
 	locl_dir="$locl_dir/"
 fi
 
-bckup_file="$(basename $locl_dir)-$(date +%Y%m%d).tar.xz"
+bckup_file="$(basename $locl_dir)-$(date +%Y%m%d).[gpg-encrypted].tar.xz"
 
 ## Use sudo depending on which user the directory belongs too.
 if [ "test -O $locl_dir" = "0" ]; then
 	## Compress the chosen directory.
-	dialog --infobox "Making a tar.xz archive of the chosen directory (it might take a while)..." 6 65 ; sleep 5
+	dialog --infobox "Making a tar.xz archive of the chosen directory '$locl_dir'\n(it might take a while)..." 8 80 ; sleep 5
 	XZ_OPT=-9 tar cJf $bckup_file $locl_dir &> /dev/null
 else
 	## Compress the chosen directory as root.
-	dialog --infobox "Making a tar.xz archive of the chosen directory (it might take a while)..." 6 65 ; sleep 5
+	dialog --infobox "Making a tar.xz archive of the chosen directory '$locl_dir'\n(it might take a while)..." 8 80 ; sleep 5
 	sudo su -c "XZ_OPT=-9 tar cJf $bckup_file $locl_dir &> /dev/null"
 fi
 
+## Encrypt the file.
+dialog --infobox "Encrypting the file as it will be sent to Copy.com through simple http which is not safe... Enter a password and make sure to remember it." 6 75 ; sleep 10
+gpg -c $bckup_file
+rm -f $bckup_file
+mv $bckup_file.gpg $bckup_file
+
 ## Whether to send the file to Copy.com or not.
-dialog --title "Send files to Copy.com?" --yesno "Do you wish to send '$(pwd)/$bckup_file' ($(du -h $bckup_file|cut -f1))\nto Copy.com?" 8 65
+dialog --title "Send files to Copy.com?" --yesno "Do you wish to send '$(pwd)/$bckup_file' ($(du -h $bckup_file|cut -f1)) to Copy.com?" 8 80
 
 if [ "$?" = "0" ]; then
 	## Check if destination dir exist. If not, create it.
 	if $CopyCmd ls $dest_dir|grep -G 'Error'; then
-		${CopyCmd} mkdir $dest_dir
-		dialog --infobox "The destination directory did not exist on Copy. Created it." 6 65 ; sleep 5
+		$CopyCmd mkdir $dest_dir
+		dialog --infobox "The destination directory did not exist on Copy.com. Created it." 3 75 ; sleep 5
 	fi
 	$CopyCmd put -r $bckup_file $dest_dir &> /dev/null
 fi
 
 ## Whether to delete the local file or not.
-dialog --title "Discard the archived directory?" --yesno "Do you wish to delete the archived file from the local\ncomputer?\n\n$(pwd)/$bckup_file" 10 65
+dialog --title "Delete the file?" --yesno "Do you wish to delete the below file from the local computer?\nThe copy of the file sent to Copy.com will not be deleted.\n\n$(pwd)/$bckup_file" 10 75
 
 if [ "$?" = "0" ]; then
 	if [ "test -O $bckup_file" = "0" ]; then
