cleaned up an if-statement

diff --git a/backupCopy b/backupCopy
--- a/backupCopy
+++ b/backupCopy
@@ -26,31 +26,23 @@ cp_user=""
 ########################### Don't touch the below code ##############################
 
 ## Make some checks the script needs to run.
-[ -x "$(command -v {gpg,dialog})" ] && {
-	echo "Missing a dependency to run the script. Make sure to have 'gpg' and 'dialog' installed."
-	exit 1
-}
-
-[ -z "$cp_pass$cp_user" ] && {
-	echo "The username or password has not been set. Edit script and enter your credentials." 
-	exit 1
-}
+[ -x "$(command -v {gpg,dialog})" ] && echo "Missing a dependency to run the script. Make sure to have 'gpg' and 'dialog' installed." exit 1
+[[ -n $cp_pass$cp_user ]] || echo "The username or password has not been set. Edit script and enter your credentials." exit 1
 
 ## Make this common command shorter.
 CopyCmd="CopyCmd Cloud -password=$cp_pass -username=$cp_user"
 
 ## Select the local dir to backup and then destination dir on Copy and store it to a variable.
 dialog --title "Info" --msgbox "Use the arrow keys when navigating the directories. Hit space key to select a directory and return key to confirm your choice.\n\nYou can also enter the path directly to the directory." 10 60
-
-	locl_dir=$(dialog --stdout --title "Local directory to backup" --dselect $HOME 20 60)
-		[[ $? = 1 ]] && exit 1 # The user have chosen to abort if output is 1.
-
-	dest_dir=$(dialog --stdout --title "Destination on Copy" --inputbox "\nEnter the destination directory on Copy.com for which you want\nto backup to.\n\n" 12 70)
-		[[ $? = 1 ]] && exit 1 # The user have chosen to abort if output is 1.
+locl_dir=$(dialog --stdout --title "Local directory to backup" --dselect $HOME 20 60)
+	[[ $? = 1 ]] && exit 1 # The user have chosen to abort if output is 1.
+dest_dir=$(dialog --stdout --title "Destination on Copy" --inputbox "\nEnter the destination directory on Copy.com for which you want\nto backup to.\n\n" 12 70)
+	[[ $? = 1 ]] && exit 1 # The user have chosen to abort if output is 1.
 clear
+echo $dest_dir $?
 
 ## Abort if $dest_dir is empty.
-[ "$dest_dir" = "" ] && { echo "Empty destination directory. Aborted!"; exit 1; }
+[ "$dest_dir" = "" ] && echo "Empty destination directory. Aborted!" exit 1
 
 ## Check if directory variables are valid. If not, add '/' to make the variable a valid directory.
 ! grep "^/" <<<$dest_dir && dest_dir="/$dest_dir" # make sure it starts with /
@@ -67,11 +59,11 @@ if [ -e $bckup_file ]; then
 	dialog --title "Overwrite file?" --yesno "The file '$bckup_file' already exist. A 'yes' will overwrite and a 'no' will renamed it to\n\n'$keep_file'." 10 75
 
 	if [ "$?" = "0" ]; then # If yes
-        	if [ -O $bckup_file ]; then # If file belong to regular user or root
-                	rm $bckup_file
-        	else
-                	sudo su -c "rm $bckup_file"
-        	fi
+        if [ -O $bckup_file ]; then # If file belong to regular user or root
+           	rm $bckup_file
+        else
+           	sudo su -c "rm $bckup_file"
+        fi
 	else
 		if [ -O $bckup_file ]; then
 			mv $bckup_file $keep_file
@@ -91,29 +83,19 @@ function progress(){
 	done
 }
 
-## Use sudo depending on which user the directory belongs too.
-if [ -O $locl_dir ]; then
-	## Compress the chosen directory.
-	dialog --infobox "Making a tar.xz archive of the chosen directory '$locl_dir'\n\n(it might take a while)..." 8 80 ; sleep 5
-
-	progress & # start progress bar
-	myself=$!
-	XZ_OPT=-9 tar cJf $bckup_file $locl_dir &>/dev/null # compress file
-	kill $myself &>/dev/null
-	echo -n ".done."
-	echo
+## Compress the chosen directory.
+dialog --infobox "Making a tar.xz archive of the chosen directory '$locl_dir'\n\n(it might take a while)..." 8 80 ; sleep 5
+progress & # start progress bar
+MYSELF=$!
+if [ -O $locl_dir ]; then ## Use sudo depending on which user the directory belongs too.
+    XZ_OPT=-9 tar cJf $bckup_file $locl_dir &>/dev/null # compress file
 else
-        ## Compress the chosen directory.
-        dialog --infobox "Making a tar.xz archive of the chosen directory '$locl_dir'\n\n(it might take a while)..." 8 80 ; sleep 5
-
-	progress &
-        myself=$!
-	kill -s STOP $myself
-	sudo su -c "kill -s CONT $myself; XZ_OPT=-9 tar cJf $bckup_file $locl_dir &> /dev/null"
-        kill $myself &>/dev/null
-        echo -n ".done."
-        sleep 2
+    sudo su -c "XZ_OPT=-9 tar cJf $bckup_file $locl_dir &> /dev/null"
 fi
+kill $MYSELF &>/dev/null
+echo -n ".done."
+sleep 2
+
 
 ## Encrypt the file.
 dialog --title "Encrypt file with GPG" --msgbox "The file shall now be encrypted as it will be sent to Copy.com through simple http which should not be regarded as safe... Enter a password and make sure to remember it." 10 75
@@ -132,9 +114,9 @@ if [ "$?" = "0" ]; then
 	fi
 
         progress &
-        myself=$!
-	$CopyCmd put -r $bckup_file $dest_dir &> /dev/null # Send the file
-        kill $myself &>/dev/null
+        MYSELF=$!
+	    $CopyCmd put -r $bckup_file $dest_dir #&> /dev/null # Send the file
+        kill $MYSELF &>/dev/null
         echo -n ".done."
         echo
 fi
